FEATURES = (
    {
        "id": "endless_folders",
        "module": "endless_folders",
        "title": "feature_endless_folders",
        "credit": "@zwylair",
        "min_cloudylib": "2.0.0",
    },
    {
        "id": "user_info_saver",
        "module": "user_info_saver",
        "title": "feature_user_info_saver",
        "credit": "@zwylair",
        "min_cloudylib": "2.0.0",
    },
    {
        "id": "recent_actions_plus",
        "module": "recent_actions_plus",
        "title": "feature_recent_actions_plus",
        "credit": "@anivplugins",
        "min_cloudylib": None,
    },
    {
        "id": "admin_tools",
        "module": "admin_tools",
        "title": "feature_admin_tools",
        "credit": "@zwylair",
        "min_cloudylib": "2.0.0",
    },
    {
        "id": "no_forward_limit",
        "module": "no_forward_limit",
        "title": "feature_no_forward_limit",
        "credit": "@zwylair",
        "min_cloudylib": "2.0.6",
    },
    {
        "id": "ghost_mode",
        "module": "ghost_mode",
        "title": "feature_ghost_mode",
        "credit": "@cloudgmuz",
        "min_cloudylib": None,
    },
    {
        "id": "chat_ids",
        "module": "chat_ids",
        "title": "feature_chat_ids",
        "credit": "@cloudgmuz",
        "min_cloudylib": None,
    },
    {
        "id": "read_receipts",
        "module": "read_receipts",
        "title": "feature_read_receipts",
        "credit": "@cloudgmuz",
        "min_cloudylib": None,
    },
    {
        "id": "copy_link",
        "module": "copy_link",
        "title": "feature_copy_link",
        "credit": "@cloudgmuz",
        "min_cloudylib": None,
    },
    {
        "id": "anti_delete",
        "module": "anti_delete",
        "title": "feature_anti_delete",
        "credit": "@cloudgmuz",
        "min_cloudylib": None,
    },
    {
        "id": "auto_delete",
        "module": "auto_delete",
        "title": "feature_auto_delete",
        "credit": "@cloudgmuz",
        "min_cloudylib": None,
    },
    {
        "id": "chat_export",
        "module": "chat_export",
        "title": "feature_chat_export",
        "credit": "@cloudgmuz",
        "min_cloudylib": None,
    },
)
